1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [3]:
print(np.__version__)

2.1.3


3. Создайте вектор со значениями от 10 до 49 

In [4]:
vektor = np.arange(10,50)
print(vektor)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [5]:
x = np.array([10,50])
y = np.flip(x)
print(y)

[50 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [6]:
A = np.random.random((5,5))
print(A)
print(np.mean(A,axis=1))
print(np.median(A,axis=1))

[[6.13042029e-04 8.23252079e-01 5.25979508e-01 2.93434152e-01
  7.17659427e-01]
 [1.57369323e-01 4.55707226e-01 8.34679486e-01 9.63056875e-01
  7.92803269e-01]
 [1.47834788e-01 9.69533248e-02 8.82193854e-01 5.91407639e-01
  3.27024095e-01]
 [5.71444878e-02 2.99396750e-01 2.84692111e-01 9.90870446e-01
  8.57292670e-01]
 [5.79551428e-01 5.46455962e-01 1.19916074e-01 4.37860841e-01
  2.12434105e-01]]
[0.47218764 0.64072324 0.40908274 0.49787929 0.37924368]
[0.52597951 0.79280327 0.32702409 0.29939675 0.43786084]


6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [7]:
a = np.array([x for x in range(27)])

In [8]:
a=np.array([x for x in range(27)]).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [9]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

In [10]:
b=np.astype(a,int)
print(b)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [11]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [12]:
b=np.astype(a,bool)
print(b)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [13]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [14]:
rez=np.hstack((a1,a2))
print(rez)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [15]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [16]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])
res=np.vstack((a1,a2))
print(res)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
print(np.where(a==b))

(array([0, 3, 4]),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [19]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [20]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])
rez=np.dot(a,b)
print(rez)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [21]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

In [22]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [23]:
angles = np.array([3.14, 3.14/2, 6.28])

In [24]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [25]:
v = np.random.random(size=[10])
print(v)

[0.9246527  0.25457021 0.50653503 0.88476886 0.4232126  0.74466328
 0.17228014 0.6173695  0.3890617  0.86658273]


In [26]:
v = np.random.random(size=[10])
print(v)
print(np.sort(v))

[0.05992521 0.45174536 0.65454036 0.14916757 0.45608049 0.2942383
 0.80218166 0.58633192 0.61940249 0.22214833]
[0.05992521 0.14916757 0.22214833 0.2942383  0.45174536 0.45608049
 0.58633192 0.61940249 0.65454036 0.80218166]


16. Проверить, одинаковы ли два NumPy массива

In [27]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [28]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
rez = np.allclose(a,b)
print(rez)


True


17. В одномерном массиве заменить максимальный элемент на ноль

In [29]:
Z = np.random.random(10)

In [30]:
print(Z)
a=np.argmax(Z)
Z[a]=0
print(Z)

[0.91940089 0.19118385 0.78631311 0.23259264 0.97997944 0.77007398
 0.65925741 0.34046114 0.85299873 0.75381172]
[0.91940089 0.19118385 0.78631311 0.23259264 0.         0.77007398
 0.65925741 0.34046114 0.85299873 0.75381172]


18. Замените все нечетные числа одномерного массива на -1.

In [31]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[np.where(arr%2!=0)]=-1

In [33]:
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [34]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [35]:
arr=np.where(arr>30 ,10,arr)
arr=np.where(arr <5 ,10,arr)

In [36]:
print(arr)

[10 10 20 10 10  5  6 10  8 10]


20. Отсортируйте двумерный массив по столбцам

In [37]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [38]:
print(np.sort(a))

[[ 3  5 11]
 [ 4  6 15]
 [ 7  8 19]]
