### Задания по NumPy

1. Создайте массив из списка, состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [2]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Создайте массив, состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy.

In [5]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

3. Создайте массив, состоящий из двадцати нулей.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

4. Создайте двумерный массив, состоящий из двадцати единиц, в котором 5 строк и 4 столбца.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

5. Создайте массив, состоящий из пяти равномерно распределённых чисел от 3 до 7.

array([3., 4., 5., 6., 7.])

In [9]:
np.linspace(3,7,5)

array([3., 4., 5., 6., 7.])

6. Создайте двумерный массив, состоящий из 9 равномерно распределённых чисел от 3 до 7.

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

In [11]:
np.linspace(3, 7 ,9).reshape(3, 3)

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

7. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 100. Присвойте его максимальное значение переменной max_number и выведите значение этой переменной.

array([74, 48, 94, 97, 48, 91, 35, 15, 96, 56])

97

In [14]:
matrix = np.random.randint(1, 100, 10)

In [15]:
matrix

array([91, 50, 22, 26, 98, 92,  7, 52,  9, 80])

In [16]:
max_number = np.max(matrix)

In [17]:
max_number

98

8. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 20. Сформируйте новый массив, состоящий из 5 элементов первого массива, начиная со 2 по порядку. Выведите значения обоих массивов.

[ 3  7  4 15 16  1 14 20 18 10]
[ 7  4 15 16  1]


In [20]:
matrix = np.random.randint(1,20,10)
print(matrix)
new_matrix = matrix[1:6]
print(new_matrix)

[15 10 18  6  5 11  7 10 18  5]
[10 18  6  5 11]


9. Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Сформируйте новый массив, состоящий из элементов  второй и третьей строки, первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print().

In [28]:
massive = np.random.randint(3,11,12).reshape(4,3)
print(massive)
new = massive[1:3,0:2]
print(new)


[[ 7  3  5]
 [ 6  7 10]
 [ 3  5  3]
 [ 6  9  5]]
[[6 7]
 [3 5]]


[[ 5 11  4]
 [10  5  9]
 [10 11 10]
 [ 7  4  9]]
[[10  5]
 [10 11]]


10. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print().

In [31]:
array = np.random.randint(0,21,10)
print(array)
print(array[2:])

[18  9  6  5  9 19  4  3  0 16]
[ 6  5  9 19  4  3  0 16]


11. Создайте двумерный массив, состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов.  Создайте новый массив, состоящий из элементов, больших числа 3. Выведите значения обоих массивов при помощи функции print().

In [34]:
massive = np.random.randint(0,9,24).reshape(4,6)
print(massive)
new = massive[massive>3]
print(new)

[[0 4 6 6 0 0]
 [4 0 6 1 3 6]
 [3 0 6 5 0 4]
 [1 6 1 7 4 7]]
[4 6 6 4 6 6 6 5 4 6 7 4 7]


[[6 1 4 3 6 0]
 [7 0 7 2 2 9]
 [1 6 4 8 0 7]
 [5 7 4 7 1 2]]
[6 4 6 7 7 9 6 4 8 7 5 7 4 7]


12. Создайте массив, состоящий из 10 случайных целых чисел из диапазона от 1 до 20. Cоздайте новый массив, состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов, а также их сумму.

[ 5  4  7  8 20  9 19  5  6  4]
[ 2  3  4  5  6  7  8  9 10 11]
[ 7  7 11 13 26 16 27 14 16 15]


In [37]:
massive1 = np.random.randint(1, 20, 10)
newMassive = np.arange(2, 12)
sumMassive = massive1 + newMassive
print(massive1, newMassive, sumMassive, sep='\n')

[11  5 13 16 13  9  6 19  8  9]
[ 2  3  4  5  6  7  8  9 10 11]
[13  8 17 21 19 16 14 28 18 20]


13. Создайте массив, состоящий из 7 случайных целых чисел из диапазона от 0 до 9. Создайте новый массив, состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов при помощи функции print().

[7 6 6 3 9 7 4]
[21 18 18  9 27 21 12]


In [39]:
mat1 = np.random.randint(0,10,7)
print(mat1)
newmat1 = mat1 * 3
print(newmat1)

[5 4 4 5 5 6 9]
[15 12 12 15 15 18 27]


14. Создайте массив, состоящий из квадратных корней 20 элементов по порядку, начиная с 7. Выведите значение массива при помощи функции print().

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]


In [43]:
matrix1 = np.arange(7,27)
print(matrix1)
matrix2 = np.sqrt(matrix1)
print(matrix2)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]


15. Даны x = [1,2], y = [[4, 1], [2, 2]]. Найдите произведение матриц x * y и y * x.

[8 5]
[6 6]


In [47]:
x = [1,2] 
y = [[4,1],[2,2]]
print(np.dot(y,x))
print(np.dot(x,y))

[6 6]
[8 5]


16. Даны x = [[1, 0], [0, 1]], y = [[4, 1], [2, 2], [1, 1]]. Найдите произведение матриц.

[[4 1]
 [2 2]
 [1 1]]


17. Создайте массив x, состоящий из 10 чисел от 0 до 9. Если элемент x меньше 3, замените его на 3. И если элемент x больше 7, замените его на 7. 

[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 4 5 6 7 7 7]


18. Создайте массив x = np.array([1, 3, 0, -1, -3]). Вычислите поэлементно знак x (sign x).

array([ 1,  1,  0, -1, -1])

array([ 1,  1,  0, -1, -1])

19. Дана матрица M = [[0 5 9 8 2], [3 7 4 1 6]]. Найдите максимальное и минимальное значения и их индексы по строкам и столбцам.

[9 7]
[2 1]
[0 1]
[0 3]
[3 7 9 8 6]
[1 1 0 0 1]
[0 5 4 1 2]
[0 0 1 1 0]


20. Создайте массив размерности 3 на 3, состоящий из чисел от 1 до 9. Вычислите среднее значение, медиану, стандартное отклонение и дисперсию.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
mean= 5.0
median= 5.0
std= 2.581988897471611
variance= 6.666666666666667
